#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo "https://github.com/stefan-guggisberg/hello-helix.git#master"
    # local development repository.
    #- &localRepo "http://localhost/local/default.git"
  strains:
    base:
      &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo

    proxy:
      &proxystrain
      origin: https://adobedocs.github.io/developer-support/

strains:
  - name: default
    <<: *basestrain
    package: sguggisb/a022269a150bbcc307f7e9c08b9a33b4937ea80f

  - name: www
    <<: *basestrain
    url: https://www.project-helix.info/
    directoryIndex: index.html
    package: sguggisb/a022269a150bbcc307f7e9c08b9a33b4937ea80f

  - name: demo
    <<: *basestrain
    url: https://demo.project-helix.info/
    directoryIndex: index.html
    package: sguggisb/a022269a150bbcc307f7e9c08b9a33b4937ea80f

  - name: dev
    <<: *basestrain
    url: https://dev.project-helix.info/
    directoryIndex: index.html
    package: sguggisb/a022269a150bbcc307f7e9c08b9a33b4937ea80f

  - name: support
    <<: *proxystrain
    url: https://stefan.project-helix.info/support
