#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo "https://github.com/stefan-guggisberg/hello-helix.git#master"
    # local development repository.
    #- &localRepo "http://localhost/local/default.git"
  strains:
    base:
      &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo

    proxy:
      &proxystrain
      origin: https://adobedocs.github.io/dev-support

strains:
  - name: default
    <<: *basestrain
    package: sguggisb/a3fed75ed24ae1d37c1623a5692222562c66ae74

  - name: www
    <<: *basestrain
    url: https://www.project-helix.info/
    directoryIndex: index.html
    package: sguggisb/a3fed75ed24ae1d37c1623a5692222562c66ae74

  - name: demo
    <<: *basestrain
    url: https://demo.project-helix.info/
    directoryIndex: index.html
    package: sguggisb/a3fed75ed24ae1d37c1623a5692222562c66ae74

  - name: dev
    <<: *basestrain
    url: https://dev.project-helix.info/
    directoryIndex: index.html
    package: sguggisb/a3fed75ed24ae1d37c1623a5692222562c66ae74

  - name: support
    <<: *proxystrain
    url: https://www.project-helix.info/support
