#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo "https://github.com/stefan-guggisberg/hello-helix.git#master"
    # local development repository.
    #- &localRepo "http://localhost/local/default.git"
  strains:
    base:
      &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo

strains:
  default:
    <<: *basestrain
    package: sguggisb/4b2a3cf68dd6af827858afe464e9534a4dcf9c94

  www:
    <<: *basestrain
    url: https://www.project-helix.info/
    directoryIndex: index.html
    package: sguggisb/4b2a3cf68dd6af827858afe464e9534a4dcf9c94

  demo:
    <<: *basestrain
    url: https://demo.project-helix.info/
    directoryIndex: index.html
    package: sguggisb/4b2a3cf68dd6af827858afe464e9534a4dcf9c94

  dev:
    <<: *basestrain
    url: https://dev.project-helix.info/
    directoryIndex: index.html
    package: sguggisb/4b2a3cf68dd6af827858afe464e9534a4dcf9c94
