#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo "https://github.com/stefan-guggisberg/hello-helix.git#master"
    # local development repository.
    #- &localRepo "http://localhost/local/default.git"
  strains:
    base: &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo

strains:
  - name: default
    <<: *basestrain

  - name: www
    <<: *basestrain
    url: https://www.project-helix.info/
    directoryIndex: index.html

  - name: demo
    <<: *basestrain
    url: https://demo.project-helix.info/
    directoryIndex: index.html

  - name: dev
    <<: *basestrain
    url: https://dev.project-helix.info/
    directoryIndex: index.html
