#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo "https://github.com/stefan-guggisberg/hello-helix.git#master"
    # local development repository.
    - &localRepo "http://localhost/local/default.git"

strains:
  local-dev:
    url: http://localhost:3000/
    code: *localRepo
    content: *localRepo
    static: *localRepo

  default:
    code: *defaultRepo
    content: *defaultRepo
    static: https://github.com/stefan-guggisberg/hello-helix.git/htdocs#master
    package: sguggisb/17e1219c6de9bef86d3a8f5252190395376786a3
